### ISSUE TITLE
Add block exchange protocol

### ISSUE THREAD

**Issue by geoah** [nimona/go-nimona#57]
# Block Exchange

Allows peers to store, and exchange data blocks between them.

## Features

* [x] Store and allow the transfer of data blocks #67
* [x] A block's key is the hash of it's payload #67
* [ ] A block's payload can be split up into multiple ordered chunks
* [ ] A block can have additional metadata of key (string) value ([]byte) pairs
* [ ] The length of the chunk will be fixes for all chunks, but can be different for each block
* [x] A peer can request a block from another peer using its key #67
* [ ] A peer can optionally request only the blocks's metadata, or even only specific chunks
* [ ] A peer can refuse returning chunks
* [ ] Blocks can optionally have white and blacklists of peers who can retrieve them
* [ ] Blocks can be optionally signed

## Notes

* Does the block's hash use only the payload or the metadata as well?
* How do we store the blocks so that retrieving specific chunks is cheap?
* Can/should we use a Patricia Merkle Tree instead of a list of chunks?
* Does it make sense to have acl at the block level?

### Wire protocols

* `https://github.com/ipfs/specs/tree/master/bitswap`
* `https://zeronet.readthedocs.io/en/latest/help_zeronet/network_protocol`
* `https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol`
* `https://github.com/ethereum/wiki/wiki/Parallel-Block-Downloads`
* `http://www.bittorrent.org/beps/bep_0003.html`
* `https://github.com/hyperledger-archives/fabric/blob/master/docs/protocol-spec.md#3.1-Message`
* `https://docs.syncthing.net/specs/bep-v1.html`
* `https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/`

### Data structures

* `https://en.bitcoin.it/wiki/Protocol_documentation#Common_structures`
* `https://github.com/hyperledger-archives/fabric/blob/master/protos/fabric.proto#L89`
* `https://wiki.theory.org/index.php/BitTorrentSpecification#Metainfo_File_Structure`
* `https://github.com/ipfs/specs/tree/master/merkledag`
* `https://docs.syncthing.net/specs/bep-v1.html#protocol-buffer-schema`

**Comment by geoah** [comment]
Block exchange replaced messenger and api is now merged #105
