### ISSUE TITLE
Add automated github releases for cmd/daemon

### ISSUE THREAD

**Issue by geoah** [nimona/go-nimona#66]
Use [goreleaser](https://goreleaser.com) to:

* [ ] Publish git tags as stable github releases (in progress: #69)
* [ ] ~Publish master as github pre-releases~
* [x] Binaries for osx (done: #68)
* [x] Binaries for windows (done: #68)
* [x] Binaries for linux (done: #68)
* [ ] Optionally brew releases (no idea how hard this actually is)

**Comment by jimeh** [comment]
> Publish master as github pre-releases

^^^ This probably isn't a good idea, cause every time someone pushes to `master` and tests pass, you'd get a new release.

**Comment by jimeh** [comment]
Hmm, ok, so GitHub Releases has a "Pre-Release" option, so that might work, specially if pre-release releases can be hidden by default from the releases page...

**Comment by geoah** [comment]
Yeah that should be fine and will allow us auto update to
Dev builds.

**Comment by geoah** [comment]
Also you can't push to master without making a pr and having at least one person other than you approve it :p

**Comment by jimeh** [comment]
So, dev/nightly/snapshot build issues:

- GitHub's releases page doesn't do much for separating pre-relrease releases from stable releases, to the point finding the latest stable release could be difficult if it ends up on page 3 behind 25 pre-releases.
- GitHub releases need a fully valid git tag on the repo. This would cause tag spam if we produced a new pre-release after every PR merge.
- `goreleaser` requires a fully valid git tag locally (not on GitHub) to build and publish a release.
- `goreleaser` can produce a build without a git tag via it's `--snapshot` option. However, it seems snapshots cannot be published to GitHub as a release.
- `goreleaser` does support GitHub's pre-release option, but not as a runtime option, so a `sed` command would be required to change it on the fly.

Potential solution:

- Some projects seem to setup a "nightlies" repository without any code in it, and only has "pre-release" releases. This seems like an ok way to avoid spamming our releases page.
- I believe `goreleaser` could be hacked to work with a separate repo, by doing the following within the build process on CircleCI:
  1. Creating a local git tag for the new nightly/snapshot build, which is never pushed to GitHub.
  2. Using `sed` or something similar to modify `.goreleaser.yml` to publish the release into a different github repo that holds nightlies only, and also to change the pre-release option to true.

Only issue I foresee is that `goreleaser` generates a changelog, which would always be from latest stable to current snapshot, there's no way to get a changelog of only from previous snapshot without storing the snapshot git tag, which we don't want to do. Potentially we could just disable changelog for snapshot builds ¯\\\_(ツ)\_/¯

**Comment by jimeh** [comment]
As discussed on Slack, consensus for now is to skip snapshot releases.

**Comment by geoah** [comment]
#69 has been merged so we should now be able to build releases! :D  
Closing this and we can re-open new ones if we need additional features/builds.
